<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title><?=$this->e($title)?> - Chocolate API</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body class="app">
    <div class="app-content">
        <main class="container">
            <?=$this->section('content')?>
        </main>
    </div>
</body>
</html>
