<?php $this->layout('layout::default', ['title' => 'Login']) ?>

<h1>Login</h1>

<form action="<?= $this->url('login-submit'); ?>" method="post">
    <div>
        <label>Name</label>
        <input type="text" name="name">
    </div>
    <div>
        <label>Surname</label>
        <input type="text" name="surname">
    </div>
    <br>
    <div>
        <input type="submit" value="Login">
    </div>
</form>
