<?php $this->layout('layout::default', ['title' => 'Login']) ?>

<h1>Login</h1>

<form action="<?= $this->url('login-submit'); ?>" method="post">
    <div>
        <label>Username</label>
        <input type="text" name="username">
    </div>
    <div>
        <label>Password</label>
        <input type="password" name="password">
    </div>
    <br>
    <div>
        <input type="submit" value="Login">
    </div>
</form>
